### PR TITLE
logs are now placed in logging directory and split into daily files

### PR DESCRIPTION
**Pull request by flumi3**
Since the size of the log file can be MASSIVE very quickly, it would be better to split them into several files and place them into a seperate folder.

With this change, log files are now split into daily files which means that there will be a log file for every day beginning on midnight. Also, the logs will now be placed into a seperate folder called "logs" with a date appendix.

### CODE REVIEW

**Comment by alecsiemerink** [comment]
This would be great. Also for when using this as a container, for persistence reasons.

**Comment by Jrjy3** [comment]
I was planning to add a feature like this at some point in the future! You beat me to it. I'll test this out later today.

**Comment by Jrjy3** [comment]
Accidentally merged while trying to merge with my fork for testing. Whoops...

**Comment by Jrjy3** [comment]
@flumi3 Could you please resubmit this pull request? Github doesn't allow you to re-open a pull request after it has been merged.

**Comment by flumi3** [comment]
Sure! I'll do it as soon as I'm at home again

**Comment by Jrjy3** [comment]
@flumi3 Thanks! Sorry about the accidental merge and revert. I'm testing this PR now and it seems like it's working for me. After it rotates the log files at midnight tonight, I'll let Cryptomaton know that I vote for it to be merged!

**Pull request merged**
