### PR TITLE
Solved Repo Install Error ..

### PR DESCRIPTION
**Pull request by thealidev**

### CODE REVIEW

**Comment by Linus045** [comment]
I don't really see the use of this PR.
It should be clear to use python version 3.
Also the command on Windows is acutally just `python` so it wouldn't work there.

If you want to, you can make a more descriptive explanation on how to set it up, but I think there are already plenty of guides out there on how to install and use python.

**Review by thealidev — COMMENTED** [review]
Updated

**Comment by thealidev** [comment]
Now Its Better Explained ..

**Comment by Linus045** [comment]
I still don't see the purpose of this PR.
It is clear to run the script using python.
There are a multitude of ways to do this depending on the OS and other factors (Windows PATH, Linux python/python3 aliases, etc.).

I don't think its useful to clutter the README.md with every possible way to use python, people can google that or ask in the discord if they really need additional help with their specific OS.
The purpose of the README is to have all minimum steps required to install and use the bot, which it currently already provides.

**Comment by thealidev** [comment]
It Uses Better Exception ..
For Both Windows And Linux ..

**Comment by Linus045** [comment]
I don't see the purpose of this PR, therefore I'm gonna close it.

**Pull request closed without merging**
