### PR TITLE
Running Docker container as a non-privilleged user

### PR DESCRIPTION
**Pull request by warren-ru**
Running the app as a root user is not a good practice.

### CODE REVIEW

**Comment by Linus045** [comment]
I'm not that familiar with Docker so I really appreciate this PR, thanks.
I tested this locally and everything seems to work fine.
I will merge it into develop and not master, I will be available for everyone with the next release.

**Review by Linus045 — APPROVED** [review]

**Comment by warren-ru** [comment]
For further development of Docker compatibility we should be able to configure the app with environment variables.
Built-in config files is not a good idea

**Comment by Linus045** [comment]
I like the general idea of that, although I'm unsure on how to implement that with the current setup.
We should discuss this on Discord at some time.

**Comment by warren-ru** [comment]
We could do this at least for auth.yml as a starting point.
Cause auth.yml contains secrets.

**Pull request merged**
