### PR TITLE
Fixed concatenation errors

### PR DESCRIPTION
**Pull request by iamtodor**
logging improvement

### CODE REVIEW

**Comment by iamtodor** [comment]
Creds to @prastiwari with his PR https://github.com/CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins/pull/38

**Review by DominicFrei — APPROVED** [review]
LGTM :+1:

**Comment by iamtodor** [comment]
PR #38 shall be closed without merging once this one will be merged
cc @DominicFrei

**Comment by iamtodor** [comment]
@DominicFrei please take a look at the logging improvement that I've done. I reckon it's great to have explicit `stop` along with `start`.
Please let me know what do you think?

**Comment by DominicFrei** [comment]
> @DominicFrei please take a look at the logging improvement that I've done. I reckon it's great to have explicit `stop` along with `start`. Please let me know what do you think?

It doesn't fit the initial intent of the PR anymore and was added after I approved but since it's just a couple lines of code I don't see an issue with that. Fine from my side. :+1:

**Review by DominicFrei — APPROVED** [review]

**Comment by iamtodor** [comment]
@DominicFrei Thank you. Yeah, I do agree it's not aligned with the initial purpose

**Comment by CyberPunkMetalHead** [comment]
Looks like there's a small conflict that needs to be resolved here and GitHub doesn't seem to allow me to resolve upon merging. Happy to merge this once resolved, thanks!

**Comment by iamtodor** [comment]
@CyberPunkMetalHead resolved :)

**Pull request closed without merging**
